### ISSUE TITLE
Add erase_if (introduced in C++20)

### ISSUE THREAD

**Issue by sdkrystian** [boostorg/static_string#10]

**Comment by m-peko** [comment]
Hey @sdkrystian,
are you willing to accept new contributors? I am interested into contributing to this repository so, if you could explain a bit more this feature request, it would be great. You can assigned it to me then.
Thanks

**Comment by sdkrystian** [comment]
Absolutely! All you need to do is implement the function specified [here](http://eel.is/c++draft/string.erasure#2).

**Comment by vinniefalco** [comment]
And don't forget the tests, and javadocs

**Comment by sdkrystian** [comment]
Addressed by #13
