### ISSUE TITLE
Update CI

### ISSUE THREAD

**Issue by vinniefalco** [boostorg/static_string#20]
static_string needs the same treatment as Boost.JSON: Update the CI scripts to check msvc versions 14.0, 14.1, and 14.2 on Drone. Remove Appveyor and Travis badges and scripts if they are not already removed.

**Comment by sdarwin** [comment]
A periodic update:

- A pull request is outstanding to merge the earlier Drone CI files. 
- Tested Github Actions.  
- It's failing on newer clang, msvc, and cmake.  
- gcc, and earlier clang, are successful. 
- If you'd like to include GHA, the easiest method right now is to copy the config directly from the boostorg/boost-ci repository.  That has been refreshed recently by Flamefire.
