### ISSUE TITLE
`static_wstring` should be conditionally enabled

### ISSUE THREAD

**Issue by jwt27** [boostorg/static_string#51]
Hi!

`static_wstring` fails to compile on platforms that don't have libc support
for wide-character strings.  I got it to work by defining a no-op
`std::swprintf(...)`, but obviously that isn't really a solution.

However, boost::config has feature detection macros for this: `BOOST_NO_CWCHAR`
and `BOOST_NO_SWPRINTF`.  So ideally, `static_wstring` should be conditionally
enabled based on those.

**Comment by sdkrystian** [comment]
Reasonable, I'll take care of this soon

**Comment by alandefreitas** [comment]
Please note this was probably because of the standalone library. We would need two paths here.

**Comment by sdkrystian** [comment]
@alandefreitas I'm not sure if it's worth trying to replicate `BOOST_NO_CWCHAR` in standalone.. Might be better to just check for `cwchar` in standalone?

**Comment by alandefreitas** [comment]
Probably not. Whatever is easier in standalone. We can have a separate path for boost.
