### ISSUE TITLE
The documentation link is broken

### ISSUE THREAD

**Issue by eyalroz** [boostorg/static_string#7]
The documentation link is broken right now. (not sure if the problem is with the link or the Boost website...)

**Comment by sdkrystian** [comment]
Once Boost 1.73.0 is out of beta the links will start working. For the time being you can use [the docs for the beta release](https://www.boost.org/doc/libs/1_73_0_beta1/libs/static_string/doc/html/index.html) (they are identical)

**Comment by sdkrystian** [comment]
@eyalroz Should be working now :)
