### ISSUE TITLE
Apparently there is no "web site" for static_string

### ISSUE THREAD

**Issue by DBJDBJ** [boostorg/static_string#8]
![image](https://user-images.githubusercontent.com/145155/79878817-29810d80-83ee-11ea-90c1-cd5eff113857.png)

That's what happens when I click on the URL provided ...

**Comment by vinniefalco** [comment]
https://www.boost.org/doc/libs/develop/libs/static_string/doc/html/index.html

**Comment by vinniefalco** [comment]
You have to wait until StaticString actually ships in Boost, for your link to work :) Any day now...

**Comment by DBJDBJ** [comment]
I beg to differ sir, that link is yours ... I just clicketh on thy.

**Comment by sdkrystian** [comment]
@DBJDBJ Should be working now :)

**Comment by DBJDBJ** [comment]
And it worketh...
